export const STORE_SUMMARY =
  "CraftzLk offers authentic handmade, eco-friendly, and premium homemade products crafted with care and natural ingredients. Customers love the freshness, traditional taste, beautiful packaging, and excellent quality across spices, sweets, pickles, snacks, and handmade goods. Fast delivery, friendly customer support, and secure packaging make every order a pleasant experience. Most products arrive fresh and safely within 2–4 days.";

export const SORT_OPTIONS = [
  { value: "recent", label: "Most recent" },
  { value: "highest", label: "Highest rating" },
  { value: "lowest", label: "Lowest rating" },
  { value: "only_pictures", label: "Only pictures" },
  { value: "pictures_first", label: "Pictures first" },
  { value: "videos_first", label: "Videos first" },
  { value: "most_helpful", label: "Most helpful" },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Anjula N.",
    verified: false,
    date: "05/26/2026",
    stars: 5,
    title: "Good product",
    body: "Worth for money",
    product: "Homemade Roasted Chilli Paste (180g)",
    productImg: "/images/categories_images/category-1.webp",
    hasPictures: true,
    hasVideo: false,
    helpfulCount: 12,
  },
  {
    id: 2,
    name: "Hasitha M.",
    verified: true,
    date: "05/25/2026",
    stars: 5,
    title: null,
    body: "I recently ordered the CraftzLK spice gift set and I'm genuinely impressed. The packaging feels premium, the aromas are fresh, and everything tastes homemade. Delivery was quick and customer support answered my questions right away. Definitely ordering again.",
    product: "CraftzLK Premium Spice Gift Set",
    productImg: "/images/categories_images/category-2.webp",
    hasPictures: true,
    hasVideo: true,
    helpfulCount: 28,
  },
  {
    id: 3,
    name: "Dushari R.",
    verified: true,
    date: "05/25/2026",
    stars: 5,
    title: "Great quality and authentic taste",
    body: "The lime pickle and coconut sambol paste arrived fresh and well packed. Taste is exactly like homemade — bold, natural, and not overly processed. Very happy with the quality and fast delivery.",
    product: "Grandma's Lime Pickle & Pol Sambol Combo",
    productImg: "/images/categories_images/category-3.webp",
    hasPictures: true,
    hasVideo: false,
    helpfulCount: 19,
  },
  {
    id: 4,
    name: "Tharushi P.",
    verified: true,
    date: "05/24/2026",
    stars: 5,
    title: "Perfect for gifting",
    body: "Bought the handmade sweets hamper for a family event. Everyone loved the kokis and aluwa. Beautiful presentation and eco-friendly packaging. Arrived within 2 days.",
    product: "Traditional Kokis & Aluwa Gift Pack",
    productImg: "/images/categories_images/category-4.webp",
    hasPictures: false,
    hasVideo: true,
    helpfulCount: 8,
  },
  {
    id: 5,
    name: "Chamara W.",
    verified: false,
    date: "05/23/2026",
    stars: 4,
    title: "Fresh spices, slight delay",
    body: "Turmeric and pepper powder quality is excellent — very aromatic. Delivery took one extra day but support kept me updated. Will order again.",
    product: "Organic Turmeric & Pepper Powder Set",
    productImg: "/images/categories_images/category-1.webp",
    hasPictures: false,
    hasVideo: false,
    helpfulCount: 5,
  },
  {
    id: 6,
    name: "Nilmini F.",
    verified: true,
    date: "05/22/2026",
    stars: 5,
    title: "Everyone loved it",
    body: "Gifted the CraftzLK hamper and it was a hit. Every item felt carefully made. My friend asked for the store link immediately.",
    product: "CraftzLK Handmade Gift Hamper",
    productImg: "/images/categories_images/category-2.webp",
    hasPictures: true,
    hasVideo: false,
    helpfulCount: 22,
  },
  {
    id: 7,
    name: "Roshan K.",
    verified: true,
    date: "05/21/2026",
    stars: 5,
    title: "Natural and chemical-free",
    body: "As someone who avoids additives, CraftzLK is a relief. The coconut sambol paste is now a weekly staple in our kitchen.",
    product: "Pol Sambol Paste (180g)",
    productImg: "/images/categories_images/category-3.webp",
    hasPictures: false,
    hasVideo: true,
    helpfulCount: 15,
  },
  {
    id: 8,
    name: "Savindi J.",
    verified: false,
    date: "05/20/2026",
    stars: 4,
    title: "Nice packaging",
    body: "Eco-conscious packaging and delicious treacle curd set. Fair price for handmade quality. Delivery was prompt.",
    product: "Buffalo Curd & Treacle Set",
    productImg: "/images/categories_images/category-4.webp",
    hasPictures: true,
    hasVideo: false,
    helpfulCount: 11,
  },
  {
    id: 9,
    name: "Dinesh A.",
    verified: true,
    date: "05/19/2026",
    stars: 5,
    title: "Took me back home",
    body: "Living overseas, these murukku and thala guli reminded me of home. Beautifully packed and arrived safely.",
    product: "Sri Lankan Snack Variety Pack",
    productImg: "/images/categories_images/category-1.webp",
    hasPictures: true,
    hasVideo: true,
    helpfulCount: 31,
  },
  {
    id: 10,
    name: "Iresha C.",
    verified: true,
    date: "05/18/2026",
    stars: 5,
    title: "Consistently excellent",
    body: "Third order and quality is always consistent. Dried karawala is fresh and clean. Fast delivery every time.",
    product: "Dried Karawala – Premium Quality",
    productImg: "/images/categories_images/category-2.webp",
    hasPictures: false,
    hasVideo: false,
    helpfulCount: 7,
  },
  {
    id: 11,
    name: "Manoja B.",
    verified: true,
    date: "05/17/2026",
    stars: 3,
    title: "Good taste",
    body: "Chilli flakes taste great. Would love more detailed order tracking, but everything arrived safely.",
    product: "Homemade Chilli Flakes (150g)",
    productImg: "/images/categories_images/category-3.webp",
    hasPictures: false,
    hasVideo: false,
    helpfulCount: 3,
  },
  {
    id: 12,
    name: "Sanduni L.",
    verified: false,
    date: "05/16/2026",
    stars: 5,
    title: "Love this store",
    body: "Found CraftzLK through a friend. Ordered three items and all exceeded expectations. Banana chips alone are worth five stars.",
    product: "Homemade Banana Chips (200g)",
    productImg: "/images/categories_images/category-4.webp",
    hasPictures: true,
    hasVideo: false,
    helpfulCount: 16,
  },
];

export const REVIEWS_PER_PAGE = 5;

export const FILTER_STAR_OPTIONS = [5, 4, 3, 2, 1];
