const SAMPLE_REVIEWS = [
  {
    _id: "sample-review-1",
    id: "sample-review-1",
    customerName: "Amaya Perera",
    productName: "Kandyan Silk Saree",
    productId: "sample-p1",
    rating: 5,
    review: "Beautiful craftsmanship and fast delivery. The silk quality exceeded my expectations.",
    status: "pending",
    dateCreated: "2026-06-16T10:30:00.000Z",
  },
  {
    _id: "sample-review-2",
    id: "sample-review-2",
    customerName: "Ravi Fernando",
    productName: "Handloom Cotton Saree",
    productId: "sample-p2",
    rating: 4,
    review: "Lovely texture and authentic feel. Would recommend for festive wear.",
    status: "approved",
    dateCreated: "2026-06-15T14:20:00.000Z",
  },
  {
    _id: "sample-review-3",
    id: "sample-review-3",
    customerName: "Nimali Jayawardena",
    productName: "Matte Ceramic Vase Set",
    productId: "sample-p3",
    rating: 5,
    review: "Perfect home décor piece. Packaging was secure and eco-friendly.",
    status: "approved",
    dateCreated: "2026-06-14T09:15:00.000Z",
  },
  {
    _id: "sample-review-4",
    id: "sample-review-4",
    customerName: "Kasun Silva",
    productName: "Wooden Wine Glasses",
    productId: "sample-p4",
    rating: 3,
    review: "Nice design but one glass had a minor finish issue.",
    status: "pending",
    dateCreated: "2026-06-13T16:45:00.000Z",
  },
  {
    _id: "sample-review-5",
    id: "sample-review-5",
    customerName: "Dilani Wickramasinghe",
    productName: "Ranawara Tea Powder",
    productId: "sample-p5",
    rating: 5,
    review: "Authentic herbal tea with a wonderful aroma. Will order again.",
    status: "approved",
    dateCreated: "2026-06-12T11:00:00.000Z",
  },
  {
    _id: "sample-review-6",
    id: "sample-review-6",
    customerName: "Tharindu Bandara",
    productName: "Cane Lounge Chair",
    productId: "sample-p6",
    rating: 2,
    review: "Product did not match the listing photos closely enough.",
    status: "rejected",
    dateCreated: "2026-06-11T08:30:00.000Z",
  },
  {
    _id: "sample-review-7",
    id: "sample-review-7",
    customerName: "Sachini Mendis",
    productName: "Batik Wall Hanging",
    productId: "sample-p7",
    rating: 4,
    review: "Vibrant colours and supports local artisans. Happy with the purchase.",
    status: "pending",
    dateCreated: "2026-06-10T13:10:00.000Z",
  },
  {
    _id: "sample-review-8",
    id: "sample-review-8",
    customerName: "Ishan Rajapaksa",
    productName: "Mask Wall Art",
    productId: "sample-p8",
    rating: 5,
    review: "Stunning traditional mask — a standout piece in our living room.",
    status: "approved",
    dateCreated: "2026-06-09T17:25:00.000Z",
  },
  {
    _id: "sample-review-9",
    id: "sample-review-9",
    customerName: "Priyanka Dissanayake",
    productName: "Clay Pottery Set",
    productId: "sample-p9",
    rating: 1,
    review: "Spam content with unrelated promotional links.",
    status: "rejected",
    dateCreated: "2026-06-08T12:00:00.000Z",
  },
  {
    _id: "sample-review-10",
    id: "sample-review-10",
    customerName: "Malith Gunasekara",
    productName: "Woven Basket Collection",
    productId: "sample-p10",
    rating: 4,
    review: "Well-made baskets, ideal for storage and gifting.",
    status: "pending",
    dateCreated: "2026-06-07T15:40:00.000Z",
  },
];

export function getReviewListSampleData() {
  return SAMPLE_REVIEWS.map((item) => ({ ...item }));
}

export function isSampleReviewId(id) {
  return String(id || "").startsWith("sample-review-");
}
