/** Demo data for admin dashboard UI — no backend required */

const now = Date.now();
const day = (offset) => new Date(now - offset * 86400000);

export const DASHBOARD_SAMPLE = {
  totalCustomers: 1284,
  totalReviews: 342,

  categoryList: [
    { _id: "cat-1", name: "Handloom Textiles", children: [{ _id: "sub-1", name: "Saris" }, { _id: "sub-2", name: "Fabrics" }] },
    { _id: "cat-2", name: "Woodcraft", children: [{ _id: "sub-3", name: "Furniture" }, { _id: "sub-4", name: "Decor" }] },
    { _id: "cat-3", name: "Pottery", children: [{ _id: "sub-5", name: "Vases" }] },
    { _id: "cat-4", name: "Jewellery", children: [] },
    { _id: "cat-5", name: "Bamboo Crafts", children: [] },
  ],

  products: [
    {
      id: "p1",
      _id: "p1",
      name: "Kandyan Handloom Saree",
      catName: "Handloom Textiles",
      countInStock: 24,
      price: 12500,
      rating: 4.8,
      images: ["https://images.unsplash.com/photo-1610030469667-1ccfc00d50bf?w=200&h=200&fit=crop"],
    },
    {
      id: "p2",
      _id: "p2",
      name: "Teak Wood Carved Bowl",
      catName: "Woodcraft",
      countInStock: 8,
      price: 8900,
      rating: 4.6,
      images: ["https://images.unsplash.com/photo-1610701596007-3a61ce877b5d?w=200&h=200&fit=crop"],
    },
    {
      id: "p3",
      _id: "p3",
      name: "Clay Lotus Vase",
      catName: "Pottery",
      countInStock: 0,
      price: 4500,
      rating: 4.5,
      images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=200&h=200&fit=crop"],
    },
    {
      id: "p4",
      _id: "p4",
      name: "Silver Filigree Pendant",
      catName: "Jewellery",
      countInStock: 15,
      price: 15600,
      rating: 4.9,
      images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=200&h=200&fit=crop"],
    },
    {
      id: "p5",
      _id: "p5",
      name: "Woven Bamboo Basket Set",
      catName: "Bamboo Crafts",
      countInStock: 3,
      price: 3200,
      rating: 4.4,
      images: ["https://images.unsplash.com/photo-1595428774223-ef5262410887?w=200&h=200&fit=crop"],
    },
    {
      id: "p6",
      _id: "p6",
      name: "Heritage Batik Wall Hanging",
      catName: "Handloom Textiles",
      countInStock: 12,
      price: 7800,
      rating: 4.7,
      images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=200&h=200&fit=crop"],
    },
    {
      id: "p7",
      _id: "p7",
      name: "Draft Product Sample",
      catName: "",
      countInStock: 0,
      price: 0,
      rating: 0,
      images: [],
    },
  ],

  orders: [
    {
      _id: "o1",
      name: "Amaya Perera",
      email: "amaya@example.com",
      userid: "u1",
      amount: "18500",
      status: "completed",
      date: day(0),
      products: [
        { productId: "p1", productTitle: "Kandyan Handloom Saree", quantity: 1, subTotal: 12500, catName: "Handloom Textiles" },
        { productId: "p4", productTitle: "Silver Filigree Pendant", quantity: 1, subTotal: 6000, catName: "Jewellery" },
      ],
    },
    {
      _id: "o2",
      name: "Ravi Fernando",
      email: "ravi@example.com",
      userid: "u2",
      amount: "8900",
      status: "processing",
      date: day(0),
      products: [{ productId: "p2", productTitle: "Teak Wood Carved Bowl", quantity: 1, subTotal: 8900, catName: "Woodcraft" }],
    },
    {
      _id: "o3",
      name: "Nethmi Silva",
      email: "nethmi@example.com",
      userid: "u3",
      amount: "4500",
      status: "pending",
      date: day(1),
      products: [{ productId: "p3", productTitle: "Clay Lotus Vase", quantity: 1, subTotal: 4500, catName: "Pottery" }],
    },
    {
      _id: "o4",
      name: "Kasun Jayawardena",
      email: "kasun@example.com",
      userid: "u4",
      amount: "25600",
      status: "completed",
      date: day(1),
      products: [
        { productId: "p1", productTitle: "Kandyan Handloom Saree", quantity: 2, subTotal: 25000, catName: "Handloom Textiles" },
      ],
    },
    {
      _id: "o5",
      name: "Dilani Wickramasinghe",
      email: "dilani@example.com",
      userid: "u5",
      amount: "3200",
      status: "cancelled",
      date: day(2),
      products: [{ productId: "p5", productTitle: "Woven Bamboo Basket Set", quantity: 1, subTotal: 3200, catName: "Bamboo Crafts" }],
    },
    {
      _id: "o6",
      name: "Amaya Perera",
      email: "amaya@example.com",
      userid: "u1",
      amount: "7800",
      status: "completed",
      date: day(3),
      products: [{ productId: "p6", productTitle: "Heritage Batik Wall Hanging", quantity: 1, subTotal: 7800, catName: "Handloom Textiles" }],
    },
    {
      _id: "o7",
      name: "Tharindu Bandara",
      email: "tharindu@example.com",
      userid: "u6",
      amount: "15600",
      status: "completed",
      date: day(4),
      products: [{ productId: "p4", productTitle: "Silver Filigree Pendant", quantity: 1, subTotal: 15600, catName: "Jewellery" }],
    },
    {
      _id: "o8",
      name: "Sachini Mendis",
      email: "sachini@example.com",
      userid: "u7",
      amount: "6400",
      status: "returned",
      date: day(5),
      products: [
        { productId: "p2", productTitle: "Teak Wood Carved Bowl", quantity: 1, subTotal: 6400, catName: "Woodcraft" },
      ],
    },
    {
      _id: "o9",
      name: "Ishan Rajapaksa",
      email: "ishan@example.com",
      userid: "u8",
      amount: "22400",
      status: "completed",
      date: day(6),
      products: [
        { productId: "p1", productTitle: "Kandyan Handloom Saree", quantity: 1, subTotal: 12500, catName: "Handloom Textiles" },
        { productId: "p6", productTitle: "Heritage Batik Wall Hanging", quantity: 1, subTotal: 9900, catName: "Handloom Textiles" },
      ],
    },
    {
      _id: "o10",
      name: "Maya Gunaratne",
      email: "maya@example.com",
      userid: "u9",
      amount: "11200",
      status: "processing",
      date: day(10),
      products: [
        { productId: "p4", productTitle: "Silver Filigree Pendant", quantity: 1, subTotal: 11200, catName: "Jewellery" },
      ],
    },
    {
      _id: "o11",
      name: "Ruwan Peiris",
      email: "ruwan@example.com",
      userid: "u10",
      amount: "9800",
      status: "pending",
      date: day(14),
      products: [{ productId: "p6", productTitle: "Heritage Batik Wall Hanging", quantity: 1, subTotal: 9800, catName: "Handloom Textiles" }],
    },
    {
      _id: "o12",
      name: "Chathuri Dias",
      email: "chathuri@example.com",
      userid: "u11",
      amount: "45000",
      status: "completed",
      date: day(20),
      products: [
        { productId: "p1", productTitle: "Kandyan Handloom Saree", quantity: 3, subTotal: 37500, catName: "Handloom Textiles" },
        { productId: "p2", productTitle: "Teak Wood Carved Bowl", quantity: 1, subTotal: 7500, catName: "Woodcraft" },
      ],
    },
    {
      _id: "o13",
      name: "Lahiru Kumara",
      email: "lahiru@example.com",
      userid: "u12",
      amount: "15600",
      status: "completed",
      date: day(35),
      products: [{ productId: "p4", productTitle: "Silver Filigree Pendant", quantity: 1, subTotal: 15600, catName: "Jewellery" }],
    },
    {
      _id: "o14",
      name: "Anjali Nair",
      email: "anjali@example.com",
      userid: "u13",
      amount: "7800",
      status: "completed",
      date: day(45),
      products: [{ productId: "p6", productTitle: "Heritage Batik Wall Hanging", quantity: 1, subTotal: 7800, catName: "Handloom Textiles" }],
    },
    {
      _id: "o15",
      name: "Priya Sharma",
      email: "priya@example.com",
      userid: "u14",
      amount: "18900",
      status: "completed",
      date: day(60),
      products: [
        { productId: "p2", productTitle: "Teak Wood Carved Bowl", quantity: 2, subTotal: 17800, catName: "Woodcraft" },
      ],
    },
  ],
};

export function getDashboardSampleData() {
  return {
    orders: DASHBOARD_SAMPLE.orders,
    products: DASHBOARD_SAMPLE.products,
    catData: { categoryList: DASHBOARD_SAMPLE.categoryList },
    totalCustomers: DASHBOARD_SAMPLE.totalCustomers,
    totalReviews: DASHBOARD_SAMPLE.totalReviews,
  };
}
