const ORDER_ITEM_PLACEHOLDERS = [
  "{{customerName}}",
  "{{storeName}}",
  "{{orderNumber}}",
  "{{orderDate}}",
  "{{paymentMethod}}",
  "{{paymentStatus}}",
  "{{itemsList}}",
  "{{subtotal}}",
  "{{deliveryCharge}}",
  "{{discount}}",
  "{{tax}}",
  "{{total}}",
  "{{deliveryAddress}}",
  "{{city}}",
  "{{postalCode}}",
  "{{phoneNumber}}",
  "{{orderViewUrl}}",
  "{{supportEmail}}",
];

const ORDER_SHIPPED_PLACEHOLDERS = [
  "{{customerName}}",
  "{{storeName}}",
  "{{orderNumber}}",
  "{{shippedDate}}",
  "{{courierName}}",
  "{{trackingNumber}}",
  "{{itemsList}}",
  "{{deliveryAddress}}",
  "{{city}}",
  "{{postalCode}}",
  "{{estimatedDeliveryDate}}",
  "{{trackingUrl}}",
  "{{supportEmail}}",
];

const ORDER_DELIVERED_PLACEHOLDERS = [
  "{{customerName}}",
  "{{storeName}}",
  "{{orderNumber}}",
  "{{deliveredDate}}",
  "{{deliveryAddress}}",
  "{{itemsList}}",
  "{{total}}",
  "{{orderViewUrl}}",
  "{{reviewUrl}}",
  "{{supportEmail}}",
];

exports.DEFAULT_NOTIFICATION_TEMPLATES = [
  {
    code: "welcome",
    name: "Welcome Email",
    channel: "email",
    category: "account",
    description: "Sent when a new customer account is welcomed to the store.",
    placeholders: ["{{customerName}}", "{{storeName}}", "{{supportEmail}}"],
    subject: "Welcome to {{storeName}}!",
    body: [
      "Hello {{customerName}},",
      "",
      "Thank you for registering with {{storeName}}. We're excited to have you on board!",
      "",
      "If you have any questions, feel free to contact our support team at {{supportEmail}}.",
      "",
      "Best regards,",
      "The {{storeName}} Team",
    ].join("\n"),
    status: "active",
  },
  {
    code: "password_reset",
    name: "Password Reset",
    channel: "email",
    category: "account",
    description: "Sent when a customer requests a password reset link.",
    placeholders: ["{{customerName}}", "{{resetUrl}}", "{{storeName}}"],
    subject: "Reset your {{storeName}} password",
    body: [
      "Hello {{customerName}},",
      "",
      "You requested a password reset for your {{storeName}} account.",
      "Open the link below to choose a new password:",
      "{{resetUrl}}",
      "",
      "This link expires in 10 minutes.",
      "",
      "If you didn't request this, you can safely ignore this email.",
      "",
      "Best regards,",
      "The {{storeName}} Team",
    ].join("\n"),
    status: "active",
  },
  {
    code: "password_changed",
    name: "Password Changed",
    channel: "email",
    category: "account",
    description: "Sent after a customer successfully changes their password.",
    placeholders: ["{{customerName}}", "{{storeName}}", "{{supportEmail}}"],
    subject: "Password Changed Successfully",
    body: [
      "Hello {{customerName}},",
      "",
      "Your password has been successfully changed.",
      "",
      "If you didn't make this change, please contact our support team immediately at {{supportEmail}}.",
      "",
      "Best regards,",
      "The {{storeName}} Team",
    ].join("\n"),
    status: "active",
  },
  {
    code: "temporary_password",
    name: "Temporary Password",
    channel: "email",
    category: "account",
    description: "Sent when a new account is created with a temporary password.",
    placeholders: ["{{customerName}}", "{{temporaryPassword}}", "{{signInUrl}}", "{{storeName}}"],
    subject: "Welcome to {{storeName}} — your temporary password",
    body: [
      "Hello {{customerName}},",
      "",
      "Thank you for joining {{storeName}}! Your account has been created successfully.",
      "",
      "Your temporary password: {{temporaryPassword}}",
      "",
      "This password expires in 24 hours.",
      "",
      "Sign in here: {{signInUrl}}",
      "",
      "We recommend changing your password after your first login.",
      "",
      "Best regards,",
      "The {{storeName}} Team",
    ].join("\n"),
    status: "active",
  },
  {
    code: "newsletter_confirm",
    name: "Newsletter Confirmation",
    channel: "email",
    category: "newsletter",
    description: "Double opt-in email asking subscribers to confirm their subscription.",
    placeholders: ["{{confirmUrl}}", "{{storeName}}", "{{unsubscribeUrl}}"],
    subject: "Confirm your {{storeName}} subscription",
    body: [
      "Hi,",
      "",
      "Thanks for joining {{storeName}}!",
      "",
      "Please confirm your email address to start receiving our latest products, offers, and maker stories.",
      "{{confirmUrl}}",
      "",
      "If you didn't request this subscription, you can safely ignore this email.",
      "",
      "Warm regards,",
      "The {{storeName}} Team",
    ].join("\n"),
    status: "active",
  },
  {
    code: "newsletter_welcome",
    name: "Newsletter Welcome",
    channel: "email",
    category: "newsletter",
    description: "Sent after a subscriber confirms their newsletter subscription.",
    placeholders: ["{{storeName}}", "{{shopUrl}}", "{{unsubscribeUrl}}"],
    subject: "Welcome to {{storeName}}",
    body: [
      "Hi there,",
      "",
      "Thank you for subscribing to {{storeName}}!",
      "",
      "You're now part of our community and will be the first to hear about:",
      "- New handcrafted products and collections",
      "- Special offers and exclusive discounts",
      "- Stories from Sri Lankan makers and artisans",
      "- Seasonal collections and featured products",
      "- News and updates from {{storeName}}",
      "",
      "Discover something special: {{shopUrl}}",
      "",
      "Thank you for supporting local craftsmanship.",
      "",
      "Warm regards,",
      "The {{storeName}} Team",
      "",
      "Unsubscribe: {{unsubscribeUrl}}",
    ].join("\n"),
    status: "active",
  },
  {
    code: "order_placed",
    name: "Order Placed",
    channel: "email",
    category: "order",
    description: "Sent when a customer successfully places a new order.",
    placeholders: ORDER_ITEM_PLACEHOLDERS,
    subject: "Order #{{orderNumber}} Received – Thank You for Your Order!",
    body: [
      "Hi {{customerName}},",
      "",
      "Thank you for shopping with {{storeName}}!",
      "",
      "We've received your order and it has been successfully placed. We're currently reviewing and preparing your order for processing.",
      "",
      "ORDER DETAILS",
      "────────────────────────────",
      "Order Number: #{{orderNumber}}",
      "Order Date: {{orderDate}}",
      "Payment Method: {{paymentMethod}}",
      "Payment Status: {{paymentStatus}}",
      "Order Status: Placed",
      "",
      "ITEMS",
      "────────────────────────────",
      "{{itemsList}}",
      "",
      "────────────────────────────",
      "Subtotal:        {{subtotal}}",
      "Delivery:        {{deliveryCharge}}",
      "Discount:        -{{discount}}",
      "Tax:             {{tax}}",
      "Total:           {{total}}",
      "",
      "DELIVERY DETAILS",
      "────────────────────────────",
      "{{customerName}}",
      "{{deliveryAddress}}",
      "{{city}}, {{postalCode}}",
      "{{phoneNumber}}",
      "",
      "WHAT'S NEXT?",
      "",
      "We'll send you another email once your order has been confirmed and is ready to move to the next stage.",
      "",
      "View Your Order: {{orderViewUrl}}",
      "",
      "Thank you for supporting local craftsmanship.",
      "",
      "Warm regards,",
      "The {{storeName}} Team",
      "",
      "Need help with your order? Contact us at {{supportEmail}}",
    ].join("\n"),
    status: "active",
  },
  {
    code: "order_confirmed",
    name: "Order Confirmed",
    channel: "email",
    category: "order",
    description: "Sent when an admin confirms the order for fulfillment.",
    placeholders: ORDER_ITEM_PLACEHOLDERS,
    subject: "Your Order #{{orderNumber}} Has Been Confirmed 🎉",
    body: [
      "Hi {{customerName}},",
      "",
      "Great news!",
      "",
      "Your order #{{orderNumber}} has been confirmed and is now being prepared for shipment.",
      "",
      "ORDER CONFIRMED",
      "────────────────────────────",
      "Order Number: #{{orderNumber}}",
      "Order Date: {{orderDate}}",
      "Payment Status: {{paymentStatus}}",
      "Order Status: Confirmed",
      "",
      "ITEMS",
      "────────────────────────────",
      "{{itemsList}}",
      "",
      "────────────────────────────",
      "Subtotal:        {{subtotal}}",
      "Delivery:        {{deliveryCharge}}",
      "Discount:        -{{discount}}",
      "Tax:             {{tax}}",
      "Total:           {{total}}",
      "",
      "DELIVERY TO",
      "────────────────────────────",
      "{{customerName}}",
      "{{deliveryAddress}}",
      "{{city}}, {{postalCode}}",
      "",
      "WHAT'S NEXT?",
      "",
      "Our team is now preparing your items carefully. Once your order has been handed over to the delivery partner, we'll send you a shipping notification with tracking information.",
      "",
      "View Order Details: {{orderViewUrl}}",
      "",
      "Thank you for choosing {{storeName}}.",
      "",
      "Warm regards,",
      "The {{storeName}} Team",
      "",
      "Need help? {{supportEmail}}",
    ].join("\n"),
    status: "active",
  },
  {
    code: "order_shipped",
    name: "Order Shipped",
    channel: "email",
    category: "order",
    description: "Sent when an admin marks the order as shipped.",
    placeholders: ORDER_SHIPPED_PLACEHOLDERS,
    subject: "Your Order #{{orderNumber}} Is On Its Way! 🚚",
    body: [
      "Hi {{customerName}},",
      "",
      "Good news — your order is on its way!",
      "",
      "Order #{{orderNumber}} has been shipped and is now with our delivery partner.",
      "",
      "SHIPPING DETAILS",
      "────────────────────────────",
      "Order Number: #{{orderNumber}}",
      "Shipped On: {{shippedDate}}",
      "Delivery Partner: {{courierName}}",
      "Tracking Number: {{trackingNumber}}",
      "Order Status: Shipped",
      "",
      "ITEMS",
      "────────────────────────────",
      "{{itemsList}}",
      "",
      "DELIVERY ADDRESS",
      "────────────────────────────",
      "{{customerName}}",
      "{{deliveryAddress}}",
      "{{city}}, {{postalCode}}",
      "",
      "ESTIMATED DELIVERY",
      "────────────────────────────",
      "{{estimatedDeliveryDate}}",
      "",
      "Track Your Order: {{trackingUrl}}",
      "",
      "Please make sure someone is available at the delivery address to receive your package.",
      "",
      "We'll let you know once your order has been successfully delivered.",
      "",
      "Thank you for shopping with {{storeName}}!",
      "",
      "Warm regards,",
      "The {{storeName}} Team",
      "",
      "Need help with your delivery? {{supportEmail}}",
    ].join("\n"),
    status: "active",
  },
  {
    code: "order_delivered",
    name: "Order Delivered",
    channel: "email",
    category: "order",
    description: "Sent when an admin marks the order as delivered.",
    placeholders: ORDER_DELIVERED_PLACEHOLDERS,
    subject: "Order #{{orderNumber}} Has Been Delivered 🎉",
    body: [
      "Hi {{customerName}},",
      "",
      "Your order has arrived!",
      "",
      "We're happy to let you know that order #{{orderNumber}} has been successfully delivered.",
      "",
      "DELIVERY DETAILS",
      "────────────────────────────",
      "Order Number: #{{orderNumber}}",
      "Delivered On: {{deliveredDate}}",
      "Delivered To: {{deliveryAddress}}",
      "Order Status: Delivered",
      "",
      "ITEMS",
      "────────────────────────────",
      "{{itemsList}}",
      "",
      "────────────────────────────",
      "Order Total: {{total}}",
      "",
      "We hope you enjoy your new products!",
      "",
      "If you have a moment, we'd love to hear about your experience.",
      "",
      "View Order: {{orderViewUrl}}",
      "Leave a Review: {{reviewUrl}}",
      "",
      "Thank you for supporting {{storeName}} and the talented makers behind our products.",
      "",
      "Warm regards,",
      "The {{storeName}} Team",
      "",
      "Need help with your order? {{supportEmail}}",
    ].join("\n"),
    status: "active",
  },
];

exports.EMAIL_TEMPLATE_CODE_MAP = {
  welcome: "welcome",
  "password-reset": "password_reset",
  "password-changed": "password_changed",
  "temporary-password": "temporary_password",
  "newsletter-confirm": "newsletter_confirm",
  "newsletter-welcome": "newsletter_welcome",
  placed: "order_placed",
  confirmed: "order_confirmed",
  shipped: "order_shipped",
  delivered: "order_delivered",
};
